# Generated by Django 3.2.12 on 2023-06-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('main_img', models.ImageField(upload_to='images')),
                ('img1', models.ImageField(upload_to='images')),
                ('img2', models.ImageField(upload_to='images')),
                ('img3', models.ImageField(upload_to='images')),
                ('img4', models.ImageField(upload_to='images')),
                ('user', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'goods',
            },
        ),
    ]
